# Generated by Django 6.0 on 2026-06-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('situacion', models.CharField(blank=True, choices=[('fonasa', 'Viene de Fonasa'), ('isapre-cara', 'Isapre muy cara'), ('isapre-subio', 'Isapre subió precio'), ('comparar', 'Quiere comparar planes')], max_length=20)),
                ('renta', models.IntegerField(blank=True, help_text='Renta imponible mensual en CLP', null=True)),
                ('cargas', models.CharField(blank=True, choices=[('solo', 'Solo/a'), ('pareja', 'Con pareja'), ('familia-chica', 'Familia pequeña (1-2 hijos)'), ('familia-grande', 'Familia grande (3+ hijos)')], max_length=20)),
                ('clinica_preferente', models.CharField(blank=True, choices=[('alemana', 'Clínica Alemana'), ('las-condes', 'Clínica Las Condes'), ('davila', 'Clínica Dávila'), ('sin-preferencia', 'Sin preferencia')], max_length=20)),
                ('ahorro_estimado_min', models.IntegerField(blank=True, null=True)),
                ('ahorro_estimado_max', models.IntegerField(blank=True, null=True)),
                ('isapres_recomendadas', models.JSONField(default=list)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('contactado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-creado'],
            },
        ),
    ]
