# Generated by Django 6.0 on 2026-06-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT sin puntos, con guión (ej: 12345678-9)', max_length=12),
        ),
    ]
