# Generated by Django 6.0 on 2026-06-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_add_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='region',
            field=models.CharField(blank=True, choices=[('rm', 'Región Metropolitana'), ('v', 'Valparaíso'), ('viii', 'Biobío'), ('ix', 'La Araucanía'), ('xiv', 'Los Ríos'), ('x', 'Los Lagos'), ('vi', "O'Higgins"), ('vii', 'Maule'), ('xvi', 'Ñuble'), ('xi', 'Aysén'), ('xii', 'Magallanes'), ('iv', 'Coquimbo'), ('iii', 'Atacama'), ('ii', 'Antofagasta'), ('i', 'Tarapacá'), ('xv', 'Arica y Parinacota')], max_length=10, verbose_name='Región'),
        ),
    ]
